"""Initial schema with all models

Revision ID: 0e7d46dcb3b4
Revises: 
Create Date: 2026-02-07 11:26:53.322390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e7d46dcb3b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pg_trgm extension for fuzzy text search
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrients'))
    )
    op.create_index(op.f('ix_nutrients_created_by_user_id'), 'nutrients', ['created_by_user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('serving_size', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('usda_fdc_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_foods_created_by_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_foods'))
    )
    op.create_index('ix_foods_brand_name', 'foods', ['brand', 'name'], unique=False)
    op.create_index(op.f('ix_foods_created_by_user_id'), 'foods', ['created_by_user_id'], unique=False)
    op.create_index('ix_foods_name_gin', 'foods', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_foods_usda_fdc_id'), 'foods', ['usda_fdc_id'], unique=True)
    op.create_index('ix_foods_user_id', 'foods', ['created_by_user_id'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_meals_created_by_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meals'))
    )
    op.create_index(op.f('ix_meals_created_by_user_id'), 'meals', ['created_by_user_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recipes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes'))
    )
    op.create_index(op.f('ix_recipes_user_id'), 'recipes', ['user_id'], unique=False)
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(length=100), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_goals')),
    sa.UniqueConstraint('user_id', 'goal_type', name='uq_user_goal_type')
    )
    op.create_index(op.f('ix_user_goals_user_id'), 'user_goals', ['user_id'], unique=False)
    op.create_table('food_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_food_logs_food_id_foods'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_food_logs_meal_id_meals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_food_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_logs'))
    )
    op.create_index(op.f('ix_food_logs_food_id'), 'food_logs', ['food_id'], unique=False)
    op.create_index(op.f('ix_food_logs_logged_at'), 'food_logs', ['logged_at'], unique=False)
    op.create_index(op.f('ix_food_logs_meal_id'), 'food_logs', ['meal_id'], unique=False)
    op.create_index(op.f('ix_food_logs_user_id'), 'food_logs', ['user_id'], unique=False)
    op.create_index('ix_food_logs_user_id_logged_at', 'food_logs', ['user_id', 'logged_at'], unique=False, postgresql_using='btree')
    op.create_table('food_nutrients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('nutrient_id', sa.Integer(), nullable=False),
    sa.Column('amount_per_serving', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_food_nutrients_food_id_foods'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrients.id'], name=op.f('fk_food_nutrients_nutrient_id_nutrients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_nutrients')),
    sa.UniqueConstraint('food_id', 'nutrient_id', name='uq_food_nutrient')
    )
    op.create_index(op.f('ix_food_nutrients_food_id'), 'food_nutrients', ['food_id'], unique=False)
    op.create_index('ix_food_nutrients_food_nutrient', 'food_nutrients', ['food_id', 'nutrient_id'], unique=False)
    op.create_index(op.f('ix_food_nutrients_nutrient_id'), 'food_nutrients', ['nutrient_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('recipe_ingredient_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_recipe_ingredients_food_id_foods'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_ingredients_recipe_id_recipes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_ingredient_id', name=op.f('pk_recipe_ingredients'))
    )
    op.create_index(op.f('ix_recipe_ingredients_food_id'), 'recipe_ingredients', ['food_id'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_recipe_id'), 'recipe_ingredients', ['recipe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_ingredients_recipe_id'), table_name='recipe_ingredients')
    op.drop_index(op.f('ix_recipe_ingredients_food_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_food_nutrients_nutrient_id'), table_name='food_nutrients')
    op.drop_index('ix_food_nutrients_food_nutrient', table_name='food_nutrients')
    op.drop_index(op.f('ix_food_nutrients_food_id'), table_name='food_nutrients')
    op.drop_table('food_nutrients')
    op.drop_index('ix_food_logs_user_id_logged_at', table_name='food_logs', postgresql_using='btree')
    op.drop_index(op.f('ix_food_logs_user_id'), table_name='food_logs')
    op.drop_index(op.f('ix_food_logs_meal_id'), table_name='food_logs')
    op.drop_index(op.f('ix_food_logs_logged_at'), table_name='food_logs')
    op.drop_index(op.f('ix_food_logs_food_id'), table_name='food_logs')
    op.drop_table('food_logs')
    op.drop_index(op.f('ix_user_goals_user_id'), table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_index(op.f('ix_recipes_user_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_meals_created_by_user_id'), table_name='meals')
    op.drop_table('meals')
    op.drop_index('ix_foods_user_id', table_name='foods')
    op.drop_index(op.f('ix_foods_usda_fdc_id'), table_name='foods')
    op.drop_index('ix_foods_name_gin', table_name='foods', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_foods_created_by_user_id'), table_name='foods')
    op.drop_index('ix_foods_brand_name', table_name='foods')
    op.drop_table('foods')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_nutrients_created_by_user_id'), table_name='nutrients')
    op.drop_table('nutrients')
    # ### end Alembic commands ###
