"""recipe system schema

Revision ID: 31036af9f10c
Revises: c78c3c13d99f
Create Date: 2026-03-21 18:05:34.661327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31036af9f10c'
down_revision: Union[str, Sequence[str], None] = 'c78c3c13d99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_recipe_versions_food_id_foods'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_versions_recipe_id_recipes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_versions')),
    sa.UniqueConstraint('recipe_id', 'version', name='uq_recipe_versions_recipe_id_version')
    )
    op.create_index(op.f('ix_recipe_versions_food_id'), 'recipe_versions', ['food_id'], unique=False)
    op.create_index(op.f('ix_recipe_versions_recipe_id'), 'recipe_versions', ['recipe_id'], unique=False)
    op.add_column('foods', sa.Column('recipe_id', sa.Integer(), nullable=True))
    op.add_column('foods', sa.Column('recipe_version', sa.Integer(), nullable=True))
    op.add_column('foods', sa.Column('is_recipe_expired', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_foods_recipe_id'), 'foods', ['recipe_id'], unique=False)
    op.create_foreign_key(op.f('fk_foods_recipe_id_recipes'), 'foods', 'recipes', ['recipe_id'], ['id'], ondelete='SET NULL')
    op.add_column('recipe_ingredients', sa.Column('portion_description', sa.String(length=200), nullable=True))
    op.add_column('recipes', sa.Column('servings', sa.Numeric(precision=10, scale=2), server_default='1', nullable=False))
    op.add_column('recipes', sa.Column('serving_unit', sa.String(length=50), server_default='serving', nullable=False))
    op.add_column('recipes', sa.Column('current_version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('recipes', sa.Column('current_food_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_recipes_current_food_id'), 'recipes', ['current_food_id'], unique=False)
    op.create_foreign_key(op.f('fk_recipes_current_food_id_foods'), 'recipes', 'foods', ['current_food_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_recipes_current_food_id_foods'), 'recipes', type_='foreignkey')
    op.drop_index(op.f('ix_recipes_current_food_id'), table_name='recipes')
    op.drop_column('recipes', 'current_food_id')
    op.drop_column('recipes', 'current_version')
    op.drop_column('recipes', 'serving_unit')
    op.drop_column('recipes', 'servings')
    op.drop_column('recipe_ingredients', 'portion_description')
    op.drop_constraint(op.f('fk_foods_recipe_id_recipes'), 'foods', type_='foreignkey')
    op.drop_index(op.f('ix_foods_recipe_id'), table_name='foods')
    op.drop_column('foods', 'is_recipe_expired')
    op.drop_column('foods', 'recipe_version')
    op.drop_column('foods', 'recipe_id')
    op.drop_index(op.f('ix_recipe_versions_recipe_id'), table_name='recipe_versions')
    op.drop_index(op.f('ix_recipe_versions_food_id'), table_name='recipe_versions')
    op.drop_table('recipe_versions')
    # ### end Alembic commands ###
