"""add unit to food_logs and extend summary nutrients

Revision ID: c78c3c13d99f
Revises: aa9b43d01326
Create Date: 2026-03-06 14:09:57.045964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78c3c13d99f'
down_revision: Union[str, Sequence[str], None] = 'aa9b43d01326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_logs', sa.Column('unit', sa.String(length=100), nullable=True))
    op.add_column('user_summary_nutrients', sa.Column('display_name', sa.String(length=50), nullable=True))
    op.add_column('user_summary_nutrients', sa.Column('display_unit', sa.String(length=20), nullable=True))
    op.add_column('user_summary_nutrients', sa.Column('formula', sa.Text(), nullable=True))
    op.alter_column('user_summary_nutrients', 'nutrient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_summary_nutrients', 'nutrient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_summary_nutrients', 'formula')
    op.drop_column('user_summary_nutrients', 'display_unit')
    op.drop_column('user_summary_nutrients', 'display_name')
    op.drop_column('food_logs', 'unit')
    # ### end Alembic commands ###
