"""Application-wide constants."""

# Food Search
FOOD_SEARCH_SIMILARITY_THRESHOLD = 0.1
FOOD_SEARCH_DEFAULT_LIMIT = 20
FOOD_SEARCH_MAX_LIMIT = 100

# AI
AI_MAX_TOKENS = 1024
AI_INPUT_MAX_LENGTH = 500
AI_MEAL_HINT_MAX_LENGTH = 50
AI_MAX_MATCHES_PER_ITEM = 3
AI_MAX_MATCHES_LIMIT = 10
AI_HIGH_SIMILARITY_THRESHOLD = 0.8
AI_LOW_CONFIDENCE_THRESHOLD = 0.7

# Food Matching
FOOD_MATCH_SIMILARITY_THRESHOLD = 0.3

# Auth
PASSWORD_MIN_LENGTH = 8
USERNAME_MIN_LENGTH = 3
USERNAME_MAX_LENGTH = 50
JWT_MIN_SECRET_LENGTH = 32
JWT_MIN_UNIQUE_CHARS = 10

# Pagination
DEFAULT_PAGE_OFFSET = 0
